workflow: 'GitFlow/v1'
major-version-bump-message: "^(build|chore|feat|fix|perf|refactor|revert)(\\([\\w\\s-,/\\\\]*\\))?(!:|:.*\\n\\n((.+\\n)+\\n)?BREAKING CHANGE:\\s.+)"
minor-version-bump-message: "^(feat)(\\([\\w\\s-,/\\\\]*\\))?:"
patch-version-bump-message: "^(fix|perf)(\\([\\w\\s-,/\\\\]*\\))?:"
no-bump-message: "^(ci|docs|style|test)(\\([\\w\\s-,/\\\\]*\\))?:"
commit-message-incrementing: Enabled
branches:
  develop:
    label: beta
